server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        port: 9080
    gateway:
      routes:
        - id: center
          uri: http://127.0.0.1:8000
          predicates:
            - Path=/platform/api/center/**
        - id: interface
          uri: http://127.0.0.1:8010
          predicates:
            - Path=/platform/api/interface/**

  datasource:
    url: jdbc:mysql://localhost:3306?useSSL=false&characterEncoding=utf-8
    username: root
    password: Wd.020518
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: top/whiteleaf03/api/modal/entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
  file:
    name: WindyApi-Gateway.log
